---
- name: Install Java, Docker and Jenkins
  hosts: local
  become: yes
 
  tasks:
 
    # ---------------- System Update ----------------
    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: yes
 
    # ---------------- Java ----------------
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
 
    # ---------------- Docker ----------------
    - name: Install prerequisites for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
 
    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
      args:
        creates: /usr/share/keyrings/docker.gpg
 
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
 
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
 
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
 
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
 
    # ---------------- Jenkins ----------------
    - name: Add Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      args:
        creates: /usr/share/keyrings/jenkins-keyring.asc
 
    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
 
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
 
    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes